### ISSUE TITLE
서버비용 절감

### ISSUE THREAD

**Issue by lens0021** [femiwiki/mediawiki#241]
선택지가 많다.

1. 전부 버리고 GCP 프리티어로 이사
2. Azure 프리티어로 이사
3. 이메일 바꾼 뒤, 새 AWS 프리티어로 이사
4. AWS Lightsail로 이사
5. AWS에 RI 걸기

#### Todos
 - [x] 일단 도쿄리전으로 이사
 - [ ] 테스트서버 스팟 인스턴스로 띄워서 비용 절감
 - [ ] 그 다음 방향 고민하기

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/RatcUQ7g) to To Do - Sep 6 at 7:05 PM
 - Hyeon Kim joined this card - Sep 6 at 7:06 PM
 - Hyeon Kim added 절차 to this card - Sep 6 at 7:07 PM
 - 낙엽 transferred this card from [FEMIWIKI](https://trello.com/b/zX0oXA4U) - Sep 11 at 2:09 AM
 - Hyeon Kim removed 절차 from this card - Sep 15 at 1:03 AM
 - Hyeon Kim moved this card from Backlog to Doing - Sep 15 at 1:03 AM
 - Hyeon Kim moved this card from Doing to Backlog - Sep 15 at 1:20 AM
 - Hyeon Kim added TODOs to this card - Sep 16 at 5:17 AM
 - Hyeon Kim completed 일단 도쿄리전으로 이사 on this card - Sep 16 at 5:17 AM
 - Hyeon Kim completed 테스트서버 스팟 인스턴스로 띄워서 비용 절감 on this card - Sep 16 at 5:18 AM
 - Hyeon Kim moved this card from Backlog to Doing - Sep 16 at 5:29 AM
 - Hyeon Kim moved this card from Doing to Backlog - Sep 19 at 6:28 PM
